DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;
CREATE TABLE user(
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL ,
  PRIMARY KEY (id)
)DEFAULT CHARSET=utf8;
CREATE TABLE meal(
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  calories INT NOT NULL ,
  PRIMARY KEY (id)
)DEFAULT CHARSET=utf8;